exclude: "vendor/"
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: pretty-format-json
    args:
    - --autofix
  - id: trailing-whitespace

- repo: https://github.com/Bahjat/pre-commit-golang
  rev: v1.0.3
  hooks:
  - id: go-fmt-import
  - id: go-vet
  - id: go-lint
  - id: go-unit-tests
  - id: go-err-check # requires github.com/kisielk/errcheck
  - id: golangci-lint # requires github.com/golangci/golangci-lint


- repo: local
  hooks:
  - id: goimports
    name: goimports
    entry: goimports -local github.com/erdii/toolbox -w
    language: system
    types: [go]

  - id: LICENSE
    name: LICENSE
    language: system
    entry: make verify-boilerplate
    exclude: ".*"
    always_run: true

  - id: go-mod-tidy
    name: go-mod-tidy
    entry: go mod tidy
    language: system
    exclude: ".*"
    always_run: true
